"use strict";
let bookTitle = "TypeScript Basics";
const libraryName = "My Library";
let numberOfBooks = 10;
let isLibraryOpen = true;
let titulo;
let autor;
let genero;
let idioma;
let precio;
let formato;
let isbn;
let descripcion;
let estado;
let ubicacion;
let fecha_publcacion;
let editorial;
let paginas;
let dimesiones;
let peso;
let disponible;
